services:
  - type: web
    name: team-page-frontend
    env: docker
    dockerfilePath: ./Dockerfile.frontend
    dockerContext: .
    plan: free
    region: oregon
    envVars:
      - key: VITE_API_URL
        value: https://team-page-backend.onrender.com

  - type: web
    name: team-page-backend
    env: docker
    dockerfilePath: ./StripeIntegration/Razropay/Dockerfile.backend
    dockerContext: .
    plan: free
    region: oregon
    envVars:
      - key: RAZORPAY_KEY_ID
        sync: false
      - key: RAZORPAY_KEY_SECRET
        sync: false
      - key: DB_USER
        value: postgres
      - key: DB_HOST
        fromDatabase:
          name: team-page-db
          property: host
      - key: DB_DATABASE
        value: clients
      - key: DB_PASSWORD
        fromDatabase:
          name: team-page-db
          property: password
      - key: DB_PORT
        value: "5432"
      - key: FRONTEND_URL
        value: https://team-page-frontend.onrender.com

databases:
  - name: team-page-db
    databaseName: clients
    user: postgres
    plan: free
    region: oregon